name: Tests
on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    name: Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'

      - name: Check compatibility with min Go version (${{ matrix.go }})
        if: matrix.go == '1.22.x'
        run: |
          set -eux
          go mod tidy -go=1.22.0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: |
          set -eux
          sudo add-apt-repository ppa:dqlite/dev -y --no-update
          sudo apt-get update

          sudo apt-get install --no-install-recommends -y \
            libdqlite-dev \
            shellcheck


      - name: Run static analysis
        run: |
          set -eux
          make check-static || echo "XXX: Ignoring failures for now"

          make -C example check-static || echo "XXX: Ignoring failures for now"

      - name: Unit tests (all)
        run: |
          set -eux
          make check-unit

          make -C example check-unit

      - name: Make example
        run: |
          set -eux
          make -C example
